### ISSUE TITLE
Filtered search by multiple post_types Array to String conversion error

### ISSUE THREAD

**Issue by tboggia** [5um17/wp-extended-search#16]
## Problem Description
<img width="498" alt="image" src="https://user-images.githubusercontent.com/17348237/191808709-93270c9a-ddc1-4462-ac3d-bfe418a596de.png">
I had a search page where the user can filter the results by taxonomies. The client asked to add filtering by content type. I thought it would be easy, but it kept giving me "array to string conversion" errors. The checkboxes are configured with name="taxonomy[]" in order to pass multiple values.

### My Extended Search configs: 
<img width="855" alt="image" src="https://user-images.githubusercontent.com/17348237/191806269-338f355a-7cb9-4656-81a8-ac705764c5f1.png">

## Solution
I ended up tracing the issue to `/includes/class-wpes-core.php:283`. That line didn't account for the possibility that the `$_GET` might be an array.

It was late and I ran out of debugging steam, but it wasn't working just using the array, but it worked by imploding it and then exploding it so I went with that. 

I'm pretty new to Wordpress and I'm a bit unclear how I keep this change in my filesystem without it being overwritten every time there is an update so I'm hoping this issue flag can help lead to a long-term fix to the plugin. Super happy to help, hit me up if you have any questions.

Patch:
```
diff --git site/web/app/plugins/wp-extended-search/includes/class-wpes-core.php site/web/app/plugins/wp-extended-search/includes/class-wpes-core.php
index ad4326ca..9cdb5acf 100644
--- site/web/app/plugins/wp-extended-search/includes/class-wpes-core.php
+++ site/web/app/plugins/wp-extended-search/includes/class-wpes-core.php
@@ -283,8 +283,13 @@ final class WPES_Core {

      // Set post types.
      if ( ! empty( $this->wpes_settings['post_types'] ) ) {
-				if ( isset( $_GET['post_type'] ) && in_array( esc_attr( $_GET['post_type'] ), (array) $this->wpes_settings['post_types'], true ) ) {
-					$query->query_vars['post_type'] = (array) esc_attr( $_GET['post_type'] );
+				$attr =  isset($_GET['post_type']) ? $_GET['post_type'] : false;
+				$attr = is_array($attr) ? implode(',', $attr) : $attr;
+
+				if ( $attr && !is_array($attr) && in_array( esc_attr( $attr ), (array) $this->wpes_settings['post_types'], true ) ) {
+					$query->query_vars['post_type'] = (array) esc_attr( $attr );
+				} elseif ( $attr && is_string($attr) ) {
+					$query->query_vars['post_type'] = (array) explode(',', $attr);
        } else {
          $query->query_vars['post_type'] = (array) $this->wpes_settings['post_types'];
        }
```

**Comment by 5um17** [comment]
Hi,

Sorry for the long delay.

Before WPES 2.0 there was no way to alter the global search setting so this code was added and users can build custom search form and search in single post type e.g. product. So this $_GET only accept string that can be single post type.
Since WPES 2.0 you can have multiple search form and settings and this code is no longer useful. Also if I add this patch to the core this will allow front-end users to search in post type which is not even selected in back end. 

I thank you for the efforts but I can not add this patch to the core as this is no longer needed. But I can suggest you alternative solution for your need. 

WPES uses [`pre_get_posts`](https://developer.wordpress.org/reference/hooks/pre_get_posts/) hook to alter the query see here https://github.com/5um17/wp-extended-search/blob/v2.1.2/includes/class-wpes-core.php#L267 
You can add your custom pre_get_posts hook (In theme or custom plugin) and alter the post type as per you need. You need to set the priority of this hook more than 500 so you can override the modifications by WPES. In callback function you can copy the code from WPES pre_get_posts callback and modify as you need.

Let me know if you need more help.

Thanks
